version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.4
    container_name: praticas-db-local
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: lab_praticas
    ports:
      - "5432:5432"
    volumes:
      - .pgdata:/var/lib/postgresql/data
